ekf_filter_node:
  ros__parameters:
    frequency: 10.0
    two_d_mode: true
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # Entrada: Odometria
    odom0: /odom
    odom0_config: [true, true, false,
                   false, false, false,
                   true, true, false,
                   false, false, false,
                   false, false, false]
    odom0_differential: false

    # Covariâncias da odometria
    odom0_pose_covariance: [0.01, 0,    0, 0, 0, 0,
                             0,    0.01, 0, 0, 0, 0,
                             0,    0,    99999, 0, 0, 0,
                             0,    0,    0, 99999, 0, 0,
                             0,    0,    0, 0, 99999, 0,
                             0,    0,    0, 0, 0, 99999]

    odom0_twist_covariance: [0.01, 0, 0, 0, 0, 0,
                              0, 0.01, 0, 0, 0, 0,
                              0, 0, 99999, 0, 0, 0,
                              0, 0, 0, 99999, 0, 0,
                              0, 0, 0, 0, 99999, 0,
                              0, 0, 0, 0, 0, 0.01]

    # Entrada: IMU
    imu0: /imu/data
    imu0_config: [false, false, false,
                  false, false, true,
                  false, false, false,
                  false, false, true,
                  false, false, false]
    imu0_remove_gravitational_acceleration: true

    # Covariâncias do IMU
    imu0_orientation_covariance: [0.001, 0, 0,
                                  0, 0.001, 0,
                                  0, 0, 0.01]
    imu0_angular_velocity_covariance: [0.01, 0, 0,
                                      0, 0.01, 0,
                                      0, 0, 0.05]
    imu0_linear_acceleration_covariance: [0.001, 0, 0,
                                          0, 0.01, 0,
                                          0, 0, 0.01]
                                          
#FIXME: NOT WORKING - MUITO RUÍDO